services:
  hydrhacked:
    image: ghcr.io/nonobzh22/hydr-hacked:latest
    container_name: hydrhacked_app
    restart: unless-stopped
    network_mode: host

    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - ./downloads:/downloads
      - ./images:/app/images

    deploy:
      resources:
        limits:
          memory: 512M
